describe('divisor', () => {
    it('3000/3', () => {
        cy.visit('http://127.0.0.1:5500/index.html')
        cy.contains('Calculadora')
        cy.get('#btn3').click()
        cy.get('#btn0').click()
        cy.get('#btn0').click()
        cy.get('#btn0').click()
        cy.get('#btnDivisor').click()
        cy.get('#btn3').click()
        cy.get('.resultado').click()
        cy.get('#visor').should('have.value', '1.000')
    }) 
    it('1450/6', () => {
        cy.visit('http://127.0.0.1:5500/index.html')
        cy.contains('Calculadora')
        cy.get('#btn1').click()
        cy.get('#btn4').click()
        cy.get('#btn5').click()
        cy.get('#btn0').click()
        cy.get('#btnDivisor').click()
        cy.get('#btn6').click()
        cy.get('.resultado').click()
        cy.get('#visor').should('have.value', '241,667')
    }) 
}) 