name: testes da calculadora

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: executando testes
        uses: cypress-io/github-action@v2
        with: 
          start: npm start
            